export const TRANSLATIONS = {
  ca: {
    appName: "MasteryLab AI",
    tagline: "Motor d'anti-repetició actiu • Grup de preguntes únic sincronitzat",
    uploadTitle: "Puja el teu material d'estudi",
    uploadProcessing: "Analitzant el document...",
    uploadDrop: "Arrossega el teu fitxer PDF o TXT aquí. Generarem un qüestionari personalitzat per ajudar-te a dominar el contingut.",
    adaptive: "Adaptatiu",
    poolSync: "Sincronitzat",
    sessionConfig: "Configuració de la sessió",
    docSource: "Origen del document",
    questionCount: "Preguntes a generar",
    questionCountSub: "Els recomptes més alts proporcionen una revisió més exhaustiva del material.",
    launchSession: "Iniciar sessió",
    analyzingText: "Analitzant el text...",
    questionOf: "Pregunta {current} de {total}",
    previous: "Anterior",
    next: "Següent pregunta",
    complete: "Finalitzar sessió",
    resultAnalysis: "Anàlisi de resultats",
    score: "Puntuació",
    accuracy: "Precisió",
    perfectMessage: "Rendiment impecable. Has demostrat un domini complet d'aquesta secció.",
    retryMessage: "Un esforç sòlid, però el domini total requereix una puntuació perfecta. Continua el cicle d'estudi adaptatiu.",
    insights: "Informació de correcció",
    providedAnswer: "Resposta proporcionada",
    correctResponse: "Resposta correcta",
    continueMastery: "Continuar el domini?",
    masterySub: "Generarem un nou conjunt de {count} preguntes. El motor de repetició garanteix que mai vegis les mateixes preguntes dues vegades.",
    launchNew: "Iniciar nova ronda",
    studyNew: "Estudiar nou document",
    objectivePerfected: "Objectiu perfeccionat",
    perfectSummary: "La teva comprensió d'aquest material és ara completa segons els estàndards d'estudi.",
    studyNext: "Estudiar següent document",
    errorTitle: "Alguna cosa ha anat malament",
    tryAgain: "Torna-ho a provar",
    replacingDoc: "Substituint el document..."
  },
  en: {
    appName: "MasteryLab AI",
    tagline: "Anti-Repetition Engine Active • Unique Question Pool Synchronized",
    uploadTitle: "Upload your study material",
    uploadProcessing: "Analyzing Document...",
    uploadDrop: "Drop your PDF or TXT file here. We'll generate a custom questionnaire to help you master the content.",
    adaptive: "Adaptive",
    poolSync: "Pool Sync",
    sessionConfig: "Session Config",
    docSource: "Document Source",
    questionCount: "Questions to generate",
    questionCountSub: "Higher counts provide a more comprehensive review of the material.",
    launchSession: "Launch Session",
    analyzingText: "Analyzing Text...",
    questionOf: "Question {current} of {total}",
    previous: "Previous",
    next: "Next Question",
    complete: "Complete Session",
    resultAnalysis: "Result Analysis",
    score: "Score",
    accuracy: "Accuracy",
    perfectMessage: "Flawless performance. You have demonstrated complete mastery of this section.",
    retryMessage: "A solid effort, but total mastery requires a perfect score. Continue the adaptive study loop.",
    insights: "Correction Insights",
    providedAnswer: "Provided Answer",
    correctResponse: "Correct Response",
    continueMastery: "Continue Mastery?",
    masterySub: "We'll generate a fresh set of {count} questions. The repetition engine ensures you never see the same questions twice.",
    launchNew: "Launch New Round",
    studyNew: "Study New Document",
    objectivePerfected: "Objective Perfected",
    perfectSummary: "Your understanding of this material is now complete according to the study standards.",
    studyNext: "Study Next Document",
    errorTitle: "Something went wrong",
    tryAgain: "Try Again",
    replacingDoc: "Replacing document..."
  },
  es: {
    appName: "MasteryLab AI",
    tagline: "Motor de anti-repetición activo • Grupo de preguntas único sincronizado",
    uploadTitle: "Sube tu material de estudio",
    uploadProcessing: "Analizando documento...",
    uploadDrop: "Arrastra tu archivo PDF o TXT aquí. Generaremos un cuestionario personalizado para ayudarte a dominar el contenido.",
    adaptive: "Adaptativo",
    poolSync: "Sincronizado",
    sessionConfig: "Configuración de la sesión",
    docSource: "Origen del documento",
    questionCount: "Preguntas a generar",
    questionCountSub: "Los recuentos más altos proporcionan una revisión más exhaustiva del material.",
    launchSession: "Iniciar sesión",
    analyzingText: "Analizando texto...",
    questionOf: "Pregunta {current} de {total}",
    previous: "Anterior",
    next: "Siguiente pregunta",
    complete: "Finalizar sesión",
    resultAnalysis: "Análisis de resultados",
    score: "Puntuación",
    accuracy: "Precisión",
    perfectMessage: "Rendimiento impecable. Has demostrado un dominio completo de esta sección.",
    retryMessage: "Un esfuerzo sólido, pero el dominio total requiere una puntuación perfecta. Continúa el ciclo de estudio adaptativo.",
    insights: "Información de corrección",
    providedAnswer: "Respuesta proporcionada",
    correctResponse: "Respuesta correcta",
    continueMastery: "¿Continuar con el dominio?",
    masterySub: "Generaremos un nuevo conjunto de {count} preguntas. El motor de repetición garantiza que nunca veas las mismas preguntas dos veces.",
    launchNew: "Iniciar nueva ronda",
    studyNew: "Estudiar nuevo documento",
    objectivePerfected: "Objetivo perfeccionado",
    perfectSummary: "Tu comprensión de este material es ahora completa según los estándares de estudio.",
    studyNext: "Estudiar siguiente documento",
    errorTitle: "Algo ha salido mal",
    tryAgain: "Intentar de nuevo",
    replacingDoc: "Reemplazando documento..."
  }
};
